/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.10.0. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Butterfly
    ( // Inputs
      input wire logic clk  // clock
    , input wire logic rst  // reset
    , input wire logic en  // enable
    , input wire logic [22:0] a
    , input wire logic [22:0] b
    , input wire logic [22:0] zeta

      // Outputs
    , output logic [22:0] outA
    , output logic [22:0] outB
    );
  logic [22:0] a_0;
  logic [22:0] b_0;
  logic [22:0] zeta_0;
  logic [22:0] result_0;
  logic [24:0] result_1;
  logic [24:0] shifted;
  logic [47:0] mWide;
  logic [46:0] c$mWide_app_arg;
  logic [23:0] xLow;
  logic [45:0] x_0;
  logic [22:0] c$app_arg;
  logic [23:0] sumWide;
  logic [22:0] result_2;
  Butterfly_types::Tuple3 x;
  logic [47:0] c$bv;
  logic [48:0] c$bv_0;
  logic [46:0] c$bv_1;
  logic [23:0] c$bv_2;
  logic [23:0] c$bv_3;
  Butterfly_types::Tuple2 result;

  assign x = {a,b,zeta};

  assign a_0 = x.Tuple3_sel0;

  assign b_0 = x.Tuple3_sel1;

  assign zeta_0 = x.Tuple3_sel2;

  assign result_0 = result_1[0+:23];

  assign result_1 = (shifted >= 25'd8380417) ? (shifted - 25'd8380417) : shifted;

  assign c$bv = (((mWide << (64'sd23)) - (mWide << (64'sd13))) + mWide);

  assign c$bv_0 = ((({{(49-46) {1'b0}},x_0}) + ({{(49-48) {1'b0}},(((mWide << (64'sd23)) - (mWide << (64'sd13))) + mWide)})) >> (64'sd24));

  assign shifted = c$bv_0[0+:25];

  assign c$bv_1 = (((c$mWide_app_arg << (64'sd23)) - (c$mWide_app_arg << (64'sd13))) - c$mWide_app_arg);

  assign c$bv_2 = (c$bv_1[0+:24]);

  assign mWide = {{(48-24) {1'b0}},(c$bv_1[0+:24])};

  assign c$mWide_app_arg = {{(47-24) {1'b0}},xLow};

  assign xLow = x_0[0+:24];

  assign x_0 = zeta_0 * b_0;

  assign result = {result_2,c$app_arg};

  assign c$app_arg = (a_0 >= result_0) ? (a_0 - result_0) : (23'd8380417 - (result_0 - a_0));

  assign sumWide = ({{(24-23) {1'b0}},a_0}) + ({{(24-23) {1'b0}},result_0});

  assign c$bv_3 = (sumWide - 24'd8380417);

  assign result_2 = (sumWide >= 24'd8380417) ? (c$bv_3[0+:23]) : (sumWide[0+:23]);

  assign outA = result.Tuple2_sel0;

  assign outB = result.Tuple2_sel1;


endmodule
`default_nettype wire

