/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.10.0. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Butterfly
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire [22:0] a
    , input wire [22:0] b
    , input wire [22:0] zeta

      // Outputs
    , output wire [22:0] outA
    , output wire [22:0] outB
    );
  wire [22:0] a_0;
  wire [22:0] b_0;
  wire [22:0] zeta_0;
  wire [22:0] result_0;
  wire [24:0] result_1;
  wire [24:0] shifted;
  wire [47:0] mWide;
  wire [46:0] c$mWide_app_arg;
  wire [23:0] xLow;
  wire [45:0] x_0;
  wire [22:0] c$app_arg;
  wire [23:0] sumWide;
  wire [22:0] result_2;
  wire [68:0] x;
  wire [47:0] c$bv;
  wire [48:0] c$bv_0;
  wire [46:0] c$bv_1;
  wire [23:0] c$bv_2;
  wire [23:0] c$bv_3;
  wire [45:0] result;

  assign x = {a,   b,   zeta};

  assign a_0 = x[68:46];

  assign b_0 = x[45:23];

  assign zeta_0 = x[22:0];

  assign result_0 = result_1[0+:23];

  assign result_1 = (shifted >= 25'd8380417) ? (shifted - 25'd8380417) : shifted;

  assign c$bv = (((mWide << (64'sd23)) - (mWide << (64'sd13))) + mWide);

  assign c$bv_0 = ((({{(49-46) {1'b0}},x_0}) + ({{(49-48) {1'b0}},(((mWide << (64'sd23)) - (mWide << (64'sd13))) + mWide)})) >> (64'sd24));

  assign shifted = c$bv_0[0+:25];

  assign c$bv_1 = (((c$mWide_app_arg << (64'sd23)) - (c$mWide_app_arg << (64'sd13))) - c$mWide_app_arg);

  assign c$bv_2 = (c$bv_1[0+:24]);

  assign mWide = {{(48-24) {1'b0}},(c$bv_1[0+:24])};

  assign c$mWide_app_arg = {{(47-24) {1'b0}},xLow};

  assign xLow = x_0[0+:24];

  assign x_0 = zeta_0 * b_0;

  assign result = {result_2,   c$app_arg};

  assign c$app_arg = (a_0 >= result_0) ? (a_0 - result_0) : (23'd8380417 - (result_0 - a_0));

  assign sumWide = ({{(24-23) {1'b0}},a_0}) + ({{(24-23) {1'b0}},result_0});

  assign c$bv_3 = (sumWide - 24'd8380417);

  assign result_2 = (sumWide >= 24'd8380417) ? (c$bv_3[0+:23]) : (sumWide[0+:23]);

  assign outA = result[45:23];

  assign outB = result[22:0];


endmodule
`default_nettype wire

